[2024-09-12T21:49:19.783+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-12T21:49:19.793+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-12T21:49:18.485933+00:00 [queued]>
[2024-09-12T21:49:19.799+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-12T21:49:18.485933+00:00 [queued]>
[2024-09-12T21:49:19.800+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-12T21:49:19.809+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-09-12 21:49:18.485933+00:00
[2024-09-12T21:49:19.815+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_python_operator_hook', 'call_api_task', 'manual__2024-09-12T21:49:18.485933+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/example_python_operator_hook.py', '--cfg-path', '/tmp/tmpgb733fkk']
[2024-09-12T21:49:19.817+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask call_api_task
[2024-09-12T21:49:19.818+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=942) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-12T21:49:19.818+0000] {standard_task_runner.py:63} INFO - Started process 944 to run task
[2024-09-12T21:49:19.847+0000] {task_command.py:426} INFO - Running <TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-12T21:49:18.485933+00:00 [running]> on host 1ab47b72986b
[2024-09-12T21:49:19.907+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_python_operator_hook' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T21:49:18.485933+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T21:49:18.485933+00:00'
[2024-09-12T21:49:19.908+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-12T21:49:19.924+0000] {base.py:84} INFO - Using connection ID 'ingestion_api' for task execution.
[2024-09-12T21:49:20.131+0000] {logging_mixin.py:188} INFO - DataFrame saved to PostgreSQL successfully.
[2024-09-12T21:49:20.139+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-12T21:49:20.147+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-09-12T21:49:20.147+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-12T21:49:20.158+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/example_python_operator_hook.py", line 42, in call_api
    upload_to_gcs(df)
  File "/opt/airflow/dags/example_python_operator_hook.py", line 49, in upload_to_gcs
    client = hook.get_conn()
             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 169, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 308, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 285, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 362, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 213, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: The `keyfile_dict`, `key_path`, and `key_secret_name` fields are all mutually exclusive. Please provide only one value.
[2024-09-12T21:49:20.163+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=example_python_operator_hook, task_id=call_api_task, run_id=manual__2024-09-12T21:49:18.485933+00:00, execution_date=20240912T214918, start_date=20240912T214919, end_date=20240912T214920
[2024-09-12T21:49:20.172+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 69 for task call_api_task (The `keyfile_dict`, `key_path`, and `key_secret_name` fields are all mutually exclusive. Please provide only one value.; 944)
[2024-09-12T21:49:20.192+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-12T21:49:20.203+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T21:49:20.205+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
