[2024-09-03T06:12:09.108+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-03T06:12:09.121+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_2.fetch_weather_data scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T06:12:09.126+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_2.fetch_weather_data scheduled__2024-09-02T00:00:00+00:00 [queued]>
[2024-09-03T06:12:09.126+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-03T06:12:09.135+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2024-09-02 00:00:00+00:00
[2024-09-03T06:12:09.141+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T06:12:09.141+0000] {standard_task_runner.py:72} INFO - Started process 86 to run task
[2024-09-03T06:12:09.142+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_2', 'fetch_weather_data', 'scheduled__2024-09-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_2.py', '--cfg-path', '/tmp/tmpqn8ms0tk']
[2024-09-03T06:12:09.143+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask fetch_weather_data
[2024-09-03T06:12:09.178+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag_2.fetch_weather_data scheduled__2024-09-02T00:00:00+00:00 [running]> on host 670a75e9450f
[2024-09-03T06:12:09.232+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag_2' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-02T00:00:00+00:00'
[2024-09-03T06:12:09.233+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-03T06:12:09.233+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-03T06:12:09.234+0000] {logging_mixin.py:190} INFO - Current task name:fetch_weather_data state:running start_date:2024-09-03 06:12:09.121372+00:00
[2024-09-03T06:12:09.234+0000] {logging_mixin.py:190} INFO - Dag name:weather_dag_2 and current dag run status:running
[2024-09-03T06:12:09.234+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-03T06:12:09.442+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag_2.py", line 91, in fetch_weather_data
    get_weather(api_key, city, start_date, end_date)
  File "/opt/airflow/dags/weather_dag_2.py", line 61, in get_weather
    raise Exception(f"Error: Unable to fetch data (HTTP Status Code: {response.status_code})")
Exception: Error: Unable to fetch data (HTTP Status Code: 400)
[2024-09-03T06:12:09.453+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-03T06:12:09.453+0000] {logging_mixin.py:190} INFO - Task start:2024-09-03 06:12:09.121372+00:00 end:2024-09-03 06:12:09.453236+00:00 duration:0.331864
[2024-09-03T06:12:09.454+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_weather_data> dag:<DAG: weather_dag_2> dagrun:<DagRun weather_dag_2 @ 2024-09-02 00:00:00+00:00: scheduled__2024-09-02T00:00:00+00:00, state:running, queued_at: 2024-09-03 06:12:06.651534+00:00. externally triggered: False>
[2024-09-03T06:12:09.454+0000] {logging_mixin.py:190} INFO - Failure caused by Error: Unable to fetch data (HTTP Status Code: 400)
[2024-09-03T06:12:09.454+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag_2, task_id=fetch_weather_data, run_id=scheduled__2024-09-02T00:00:00+00:00, execution_date=20240902T000000, start_date=20240903T061209, end_date=20240903T061209
[2024-09-03T06:12:09.466+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-03T06:12:09.466+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task fetch_weather_data (Error: Unable to fetch data (HTTP Status Code: 400); 86)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag_2.py", line 91, in fetch_weather_data
    get_weather(api_key, city, start_date, end_date)
  File "/opt/airflow/dags/weather_dag_2.py", line 61, in get_weather
    raise Exception(f"Error: Unable to fetch data (HTTP Status Code: {response.status_code})")
Exception: Error: Unable to fetch data (HTTP Status Code: 400)
[2024-09-03T06:12:09.516+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-03T06:12:09.527+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T06:12:09.529+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
