[2024-09-15T17:02:38.706+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-15T17:02:38.717+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_python_operator_hook.upload_to_bigquery_task manual__2024-09-15T17:02:36.028829+00:00 [queued]>
[2024-09-15T17:02:38.723+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_python_operator_hook.upload_to_bigquery_task manual__2024-09-15T17:02:36.028829+00:00 [queued]>
[2024-09-15T17:02:38.724+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-15T17:02:38.733+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_to_bigquery_task> on 2024-09-15 17:02:36.028829+00:00
[2024-09-15T17:02:38.740+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_python_operator_hook', 'upload_to_bigquery_task', 'manual__2024-09-15T17:02:36.028829+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/example_python_operator_hook.py', '--cfg-path', '/tmp/tmpwyc92f3h']
[2024-09-15T17:02:38.741+0000] {standard_task_runner.py:91} INFO - Job 195: Subtask upload_to_bigquery_task
[2024-09-15T17:02:38.743+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=607) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-15T17:02:38.743+0000] {standard_task_runner.py:63} INFO - Started process 609 to run task
[2024-09-15T17:02:38.768+0000] {task_command.py:426} INFO - Running <TaskInstance: example_python_operator_hook.upload_to_bigquery_task manual__2024-09-15T17:02:36.028829+00:00 [running]> on host 81bcc4ceaa16
[2024-09-15T17:02:38.858+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_python_operator_hook' AIRFLOW_CTX_TASK_ID='upload_to_bigquery_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-15T17:02:36.028829+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-15T17:02:36.028829+00:00'
[2024-09-15T17:02:38.859+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-15T17:02:38.874+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-15T17:02:38.875+0000] {base.py:84} INFO - Using connection ID 'google_cloud_defaultt' for task execution.
[2024-09-15T17:02:38.875+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-15T17:02:38.881+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/example_python_operator_hook.py", line 36, in upload_to_bigquery
    client = hook.get_client()  # Get BigQuery client
             ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 211, in get_client
    credentials=self.get_credentials(),
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 308, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 285, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 362, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 235, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 283, in _get_credentials_using_key_path
    raise AirflowException("Unrecognised extension for key file.")
airflow.exceptions.AirflowException: Unrecognised extension for key file.
[2024-09-15T17:02:38.886+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=example_python_operator_hook, task_id=upload_to_bigquery_task, run_id=manual__2024-09-15T17:02:36.028829+00:00, execution_date=20240915T170236, start_date=20240915T170238, end_date=20240915T170238
[2024-09-15T17:02:38.894+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 195 for task upload_to_bigquery_task (Unrecognised extension for key file.; 609)
[2024-09-15T17:02:38.916+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-15T17:02:38.927+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T17:02:38.929+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
