[2024-09-09T10:38:42.087+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-09T10:38:42.100+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weatherbit_dag.fetch_weather_data manual__2024-09-09T10:38:40.223436+00:00 [queued]>
[2024-09-09T10:38:42.109+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weatherbit_dag.fetch_weather_data manual__2024-09-09T10:38:40.223436+00:00 [queued]>
[2024-09-09T10:38:42.109+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-09T10:38:42.245+0000] {taskinstance.py:2879} INFO - Executing <Task(WeatherbitOperator): fetch_weather_data> on 2024-09-09 10:38:40.223436+00:00
[2024-09-09T10:38:42.251+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=224) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-09T10:38:42.252+0000] {standard_task_runner.py:72} INFO - Started process 226 to run task
[2024-09-09T10:38:42.252+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weatherbit_dag', 'fetch_weather_data', 'manual__2024-09-09T10:38:40.223436+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/weatherbit_dag.py', '--cfg-path', '/tmp/tmpzcvj463y']
[2024-09-09T10:38:42.254+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask fetch_weather_data
[2024-09-09T10:38:42.284+0000] {task_command.py:467} INFO - Running <TaskInstance: weatherbit_dag.fetch_weather_data manual__2024-09-09T10:38:40.223436+00:00 [running]> on host 9b0d414f0647
[2024-09-09T10:38:42.335+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weatherbit_dag' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T10:38:40.223436+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-09T10:38:40.223436+00:00'
[2024-09-09T10:38:42.336+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-09T10:38:42.352+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/operators/weatherbit_operator.py", line 19, in execute
    hook = WeatherbitHook(lat=self.lat, lon=self.lon)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/hooks/weatherbit_hook.py", line 12, in __init__
    self.api_key = Variable.get('weatherbit_api_key')  # Retrieve API key from Airflow Variables
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable weatherbit_api_key does not exist'
[2024-09-09T10:38:42.364+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=weatherbit_dag, task_id=fetch_weather_data, run_id=manual__2024-09-09T10:38:40.223436+00:00, execution_date=20240909T103840, start_date=20240909T103842, end_date=20240909T103842
[2024-09-09T10:38:42.374+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-09T10:38:42.375+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task fetch_weather_data ('Variable weatherbit_api_key does not exist'; 226)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/operators/weatherbit_operator.py", line 19, in execute
    hook = WeatherbitHook(lat=self.lat, lon=self.lon)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/hooks/weatherbit_hook.py", line 12, in __init__
    self.api_key = Variable.get('weatherbit_api_key')  # Retrieve API key from Airflow Variables
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable weatherbit_api_key does not exist'
[2024-09-09T10:38:42.386+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-09T10:38:42.402+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-09T10:38:42.404+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
